spring.application.name=zona_fit
#CONEXION BASE DE DATOS MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/zona_fit_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#EVITAR QU SE CREE EL ESQUEMA DE LA BASE DE DATOS
spring.jpa.hibernate.ddl-auto=none
#DESACTIVAR TOMCAT PARA QUE NO SE LEVANTE EL SERVIDOR WEB
spring.main.web-application-type=none
# Apaga el banner de inicio de Spring Boot
spring.main.banner-mode=off
# Apaga todos los mensajes informativos de Spring, Hibernate y HikariCP
#logging.level.root=ON
# Oculta la consulta SQL (Hibernate: select c1_0.id...)
spring.jpa.show-sql=false

# Silenciar el texto técnico de las librerías
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.com.zaxxer.hikari=WARN

# Mantener visibles únicamente tus mensajes
logging.level.pb.zona_fit=INFO

